//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lostnfound.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMSTATE
    {
        public int ITEMSTATEID { get; set; }
        public int ITEMID { get; set; }
        public int USERID { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public int STATEID { get; set; }
        public string COMMENT { get; set; }
    
        public virtual ITEM ITEM { get; set; }
        public virtual STATE STATE { get; set; }
        public virtual USER USER { get; set; }
    }
}
