//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lostnfound.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEM()
        {
            this.ITEMSTATEs = new HashSet<ITEMSTATE>();
        }
    
        public int ITEMID { get; set; }
        public int REPORTERID { get; set; }
        public int CREATEDBYID { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public int ITEMTYPEID { get; set; }
        public int STATEID { get; set; }
        public System.DateTime FLDATE { get; set; }
        public int CATEGORYID { get; set; }
        public Nullable<int> COLORID { get; set; }
        public int LOCATIONID { get; set; }
        public string IMAGE { get; set; }
        public string NOTES { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual COLOR COLOR { get; set; }
        public virtual ITEMTYPE ITEMTYPE { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        public virtual REPORTER REPORTER { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEMSTATE> ITEMSTATEs { get; set; }
        public object CATEGORies { get; internal set; }
    }
}
